import type { Movie, NewsItem, Snack } from "./types";

export const CINEMA = {
  name: "Cinépolis Guararapes",
  city: "Jaboatão dos Guararapes",
  brand: "Shopping Guararapes",
  address: "Av. Barreto de Menezes, 800 — Piedade, Jaboatão dos Guararapes — PE",
  rooms: 8,
  phone: "(81) 3500-0000",
  features: ["Salas IMAX", "Macro XE", "VIP reclinável", "Bomboniere"],
};

export const GENRES = [
  "Estreias",
  "Aventura",
  "Ação",
  "Fantasia",
  "Animação",
  "Comédia",
  "Suspense",
  "Terror",
];

/** Monta a URL de imagem do TMDB. */
export function tmdb(hash: string, size: "w342" | "w500" | "w780" | "original" = "w500") {
  return `https://image.tmdb.org/t/p/${size}/${hash}.jpg`;
}

export const MOVIES: Movie[] = [
  {
    id: "m1",
    slug: "supergirl",
    title: "Supergirl",
    synopsis:
      "Quando um adversário implacável atinge perto demais de casa, Kara Zor-El embarca numa jornada interestelar de vingança e justiça ao lado de uma companhia improvável. Uma nova era do universo DC nas telonas.",
    genres: ["Ação", "Aventura"],
    durationMin: 99,
    classification: "14",
    director: "Craig Gillespie",
    cast: ["Milly Alcock", "Jason Momoa", "Eve Ridley"],
    releaseDate: "2026-06-25",
    status: "showing",
    rating: 8.3,
    poster: ["#2563eb", "#f59e0b"],
    posterUrl: tmdb("9jqZfA7eaxfXWkj9vZLQbla7c5r", "w780"),
    backdropUrl: tmdb("54KIfdTEzOliHDKx0OkzYGqAICx", "w780"),
  },
  {
    id: "m2",
    slug: "toy-story-5",
    title: "Toy Story 5",
    synopsis:
      "Quando Bonnie ganha um tablet, Buzz, Woody, Jessie e a turma encaram uma nova ameaça à hora de brincar. Diversão para toda a família.",
    genres: ["Animação", "Aventura", "Comédia"],
    durationMin: 100,
    classification: "L",
    director: "Andrew Stanton",
    cast: ["(Vozes) Tom Hanks", "Tim Allen"],
    releaseDate: "2026-06-17",
    status: "showing",
    rating: 8.0,
    poster: ["#22c55e", "#0ea5e9"],
    posterUrl: tmdb("iwEuq51BV59mm2LgZ42bWgPgagW", "w780"),
    backdropUrl: tmdb("8sSKdEmlmqF4kJUd28SqthXC4yZ", "w780"),
  },
  {
    id: "m3",
    slug: "homem-aranha-um-novo-dia",
    title: "Homem-Aranha: Um Novo Dia",
    originalTitle: "Spider-Man: Brand New Day",
    synopsis:
      "Quatro anos após os eventos de Sem Volta para Casa, Peter vive sozinho numa Nova York que esqueceu seu nome — um Homem-Aranha em tempo integral diante de uma de suas ameaças mais poderosas. Em pré-venda.",
    genres: ["Ação", "Aventura"],
    durationMin: 0,
    classification: "?",
    director: "Destin Daniel Cretton",
    cast: ["Tom Holland", "Zendaya"],
    releaseDate: "2026-07-29",
    releaseLabel: "Estreia 29/07",
    status: "coming",
    preSale: true,
    rating: 0,
    poster: ["#dc2626", "#1e3a8a"],
    posterUrl: tmdb("x0nvYzQpyJc5pdT9lMnkMuYAg0O", "w780"),
  },
  {
    id: "m4",
    slug: "mestres-do-universo",
    title: "Mestres do Universo",
    originalTitle: "Masters of the Universe",
    synopsis:
      "Após 15 anos separado, a Espada do Poder leva o príncipe Adam de volta a Eternia, dominada por Esqueleto. Para salvar seu mundo, ele precisa abraçar seu destino como He-Man.",
    genres: ["Aventura", "Fantasia", "Ação"],
    durationMin: 125,
    classification: "12",
    director: "Travis Knight",
    cast: ["Nicholas Galitzine", "Camila Mendes"],
    releaseDate: "2026-07-10",
    releaseLabel: "Estreia 10/07",
    status: "coming",
    rating: 0,
    poster: ["#ea580c", "#3b0764"],
    posterUrl: tmdb("uPuVEyoGrtoU9O2sLDhwtKPR78Z", "w780"),
  },
  {
    id: "m5",
    slug: "zootopia-2",
    title: "Zootopia 2",
    synopsis:
      "Após o maior caso da história de Zootopia, os policiais novatos Judy Hopps e Nick Wilde seguem a trilha de um grande mistério quando Gary De'Snake vira a metrópole de cabeça para baixo.",
    genres: ["Animação", "Aventura", "Comédia"],
    durationMin: 108,
    classification: "L",
    director: "Jared Bush",
    cast: ["(Vozes) Ginnifer Goodwin", "Jason Bateman"],
    releaseDate: "2026-06-12",
    status: "showing",
    rating: 7.9,
    poster: ["#f97316", "#1e40af"],
    posterUrl: tmdb("sOgzzmyHJ3uWjEU509AwrcXoE71", "w780"),
    backdropUrl: tmdb("lgotja3xMoJZbynwHfcQcJAEMWH", "w780"),
  },
  {
    id: "m6",
    slug: "avatar-fogo-e-cinzas",
    title: "Avatar: Fogo e Cinzas",
    originalTitle: "Avatar: Fire and Ash",
    synopsis:
      "Após a guerra contra a RDA, Jake Sully e Neytiri enfrentam uma nova ameaça em Pandora: o Povo das Cinzas, uma tribo Na'vi violenta liderada pela impiedosa Varang.",
    genres: ["Aventura", "Ação", "Fantasia"],
    durationMin: 198,
    classification: "12",
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"],
    releaseDate: "2026-06-05",
    status: "showing",
    rating: 8.5,
    poster: ["#0ea5e9", "#0c4a6e"],
    posterUrl: tmdb("3almrQT8GnrDjnQeWotdExjJhZm", "w780"),
    backdropUrl: tmdb("u8DU5fkLoM5tTRukzPC31oGPxaQ", "w780"),
  },
  {
    id: "m7",
    slug: "wicked-parte-2",
    title: "Wicked: Parte 2",
    originalTitle: "Wicked: For Good",
    synopsis:
      "Com uma multidão se voltando contra a Bruxa Má, Glinda e Elphaba precisam se unir uma última vez — sua amizade no centro de tudo — para mudar a si mesmas e toda Oz, para sempre.",
    genres: ["Fantasia", "Aventura"],
    durationMin: 137,
    classification: "10",
    director: "Jon M. Chu",
    cast: ["Cynthia Erivo", "Ariana Grande"],
    releaseDate: "2026-06-19",
    status: "showing",
    rating: 8.2,
    poster: ["#16a34a", "#ec4899"],
    posterUrl: tmdb("8VUn52P2qFepxG8b5W8pjS7DzCT", "w780"),
    backdropUrl: tmdb("cGbPBHKSFO7hSIjxkb3KOaGdOep", "w780"),
  },
  {
    id: "m8",
    slug: "predador-terras-selvagens",
    title: "Predador: Terras Selvagens",
    originalTitle: "Predator: Badlands",
    synopsis:
      "Banido de seu clã, um jovem Predador encontra uma aliada improvável em um androide danificado e parte numa jornada traiçoeira em busca do adversário definitivo.",
    genres: ["Ação", "Aventura"],
    durationMin: 107,
    classification: "16",
    director: "Dan Trachtenberg",
    cast: ["Elle Fanning", "Dimitrius Schuster-Koloamatangi"],
    releaseDate: "2026-06-10",
    status: "showing",
    rating: 7.7,
    poster: ["#111827", "#7f1d1d"],
    posterUrl: tmdb("f3yLlUrJDdDL8d4nxywyotN45SL", "w780"),
    backdropUrl: tmdb("82lM4GJ9uuNvNDOEpxFy77uv4Ak", "w780"),
  },
  {
    id: "m9",
    slug: "segredo-obscuro",
    title: "Segredo Obscuro",
    originalTitle: "Shell",
    synopsis:
      "Samantha Lake, uma atriz em busca de relevância, é apresentada ao mundo ultraglamouroso de Zoe Shannon, CEO da empresa de bem-estar Shell. Quando pacientes começam a desaparecer, Samantha percebe que a Shell esconde um segredo monstruoso. Terror corporal com Elisabeth Moss e Kate Hudson.",
    genres: ["Terror", "Suspense"],
    durationMin: 100,
    classification: "16",
    director: "Max Minghella",
    cast: ["Elisabeth Moss", "Kate Hudson", "Kaia Gerber"],
    releaseDate: "2026-06-18",
    status: "showing",
    rating: 6.6,
    poster: ["#7f1d1d", "#1f2937"],
    posterUrl: tmdb("lHXXpXzPv22WQCzTYMuwers5jkz", "w780"),
    backdropUrl: tmdb("yGH7ke2rbeSI4IZx90UzIrMlWLq", "w780"),
    sessionTimes: ["15:40", "18:20", "21:00", "22:00"],
  },
  {
    id: "m10",
    slug: "super-mario-galaxy-o-filme",
    title: "Super Mario Galaxy: O Filme",
    originalTitle: "The Super Mario Galaxy Movie",
    synopsis:
      "Depois de frustrar o plano de Bowser, Mario e Luigi enfrentam uma nova ameaça: Bowser Jr., decidido a libertar o pai. Ao lado de velhos e novos companheiros, os irmãos cruzam as estrelas para deter o jovem herdeiro.",
    genres: ["Animação", "Aventura", "Comédia"],
    durationMin: 98,
    classification: "L",
    director: "Aaron Horvath, Michael Jelenic",
    cast: ["(Vozes) Chris Pratt", "Anya Taylor-Joy", "Jack Black"],
    releaseDate: "2026-04-01",
    status: "showing",
    rating: 7.8,
    poster: ["#e11d48", "#1d4ed8"],
    posterUrl: tmdb("b3WeTp42eJSRuE4UZfyPCOJW4c", "w780"),
    backdropUrl: tmdb("kxQiIJ4gVcD3K6o14MJ72p5yRcE", "w780"),
  },
  {
    id: "m11",
    slug: "the-mandalorian-and-grogu",
    title: "The Mandalorian e Grogu",
    originalTitle: "The Mandalorian and Grogu",
    synopsis:
      "Com o Império caído, senhores da guerra imperiais ainda ameaçam a galáxia. A jovem Nova República recruta o lendário caçador de recompensas Din Djarin e seu aprendiz Grogu para uma nova aventura.",
    genres: ["Ficção Científica", "Aventura", "Ação"],
    durationMin: 0,
    classification: "?",
    director: "Jon Favreau",
    cast: ["Pedro Pascal", "Sigourney Weaver", "Jeremy Allen White"],
    releaseDate: "2026-05-22",
    releaseLabel: "Estreia 22/05",
    status: "coming",
    rating: 0,
    poster: ["#0f766e", "#0f172a"],
    posterUrl: tmdb("dNwaS0tnwgQRaQFPY5MbGxdmYXr", "w780"),
  },
  {
    id: "m12",
    slug: "vingadores-doutor-destino",
    title: "Vingadores: Doutor Destino",
    originalTitle: "Avengers: Doomsday",
    synopsis:
      "Vingadores, Wakandanos, Quarteto Fantástico, Thunderbolts e X-Men se unem contra Doutor Destino. Heróis de três universos distintos entram em rota de colisão diante de uma ameaça existencial sem precedentes.",
    genres: ["Ação", "Aventura", "Ficção Científica"],
    durationMin: 0,
    classification: "?",
    director: "Anthony e Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Hemsworth", "Vanessa Kirby"],
    releaseDate: "2026-12-18",
    releaseLabel: "Estreia 18/12",
    status: "coming",
    rating: 0,
    poster: ["#7f1d1d", "#111827"],
    posterUrl: tmdb("i29O7K4n3z5qB2SAJmSc0kR5dPj", "w780"),
  },
  {
    id: "m13",
    slug: "shrek-5",
    title: "Shrek 5",
    synopsis:
      "O ogro mais querido do cinema está de volta com a família Fiona para uma nova e caótica aventura no Reino Tão Tão Distante.",
    genres: ["Animação", "Comédia", "Aventura"],
    durationMin: 0,
    classification: "L",
    director: "Walt Dohrn",
    cast: ["(Vozes) Mike Myers", "Eddie Murphy", "Cameron Diaz"],
    releaseDate: "2026-12-23",
    releaseLabel: "Estreia 23/12",
    status: "coming",
    rating: 0,
    poster: ["#15803d", "#052e16"],
    posterUrl: tmdb("3U8d1K8PSgrZ0Gc8miytt17kLcW", "w780"),
  },
];

export const SNACKS: Snack[] = [
  {
    id: "combo1",
    name: "Combo Casal",
    description: "2 pipocas grandes + 2 refrigerantes 500ml",
    price: 49.9,
    emoji: "🍿",
  },
  {
    id: "combo2",
    name: "Combo Individual",
    description: "1 pipoca grande + 1 refrigerante 500ml",
    price: 32.9,
    emoji: "🥤",
  },
  {
    id: "pipoca",
    name: "Pipoca Grande",
    description: "Pipoca salgada ou doce",
    price: 24.0,
    emoji: "🍿",
  },
  {
    id: "refri",
    name: "Refrigerante 700ml",
    description: "Copo grande gelado",
    price: 16.5,
    emoji: "🥤",
  },
  {
    id: "choco",
    name: "Chocolate",
    description: "Caixa de bombons",
    price: 18.0,
    emoji: "🍫",
  },
  {
    id: "agua",
    name: "Água Mineral",
    description: "Sem gás 500ml",
    price: 7.0,
    emoji: "💧",
  },
];

export const NEWS: NewsItem[] = [
  {
    id: "n1",
    title: "'Supergirl' bate recorde de bilheteria na estreia nacional",
    date: "26/06/2026 | 18:43",
    author: "Pamela Cordeiro",
    category: "Bilheteria",
    image: ["#2563eb", "#f59e0b"],
    imageUrl: tmdb("9jqZfA7eaxfXWkj9vZLQbla7c5r", "w780"),
  },
  {
    id: "n2",
    title: "'Homem-Aranha: Um Novo Dia' abre pré-venda e ingressos esgotam em horas",
    date: "26/06/2026 | 14:21",
    author: "Rafael Lopes",
    category: "Lançamentos",
    image: ["#dc2626", "#1e3a8a"],
    imageUrl: tmdb("x0nvYzQpyJc5pdT9lMnkMuYAg0O", "w780"),
  },
  {
    id: "n3",
    title: "'Avatar: Fogo e Cinzas' lidera as sessões IMAX do fim de semana",
    date: "25/06/2026 | 09:10",
    author: "Carla Mendes",
    category: "Cinemas",
    image: ["#0ea5e9", "#0c4a6e"],
    imageUrl: tmdb("3almrQT8GnrDjnQeWotdExjJhZm", "w780"),
  },
  {
    id: "n4",
    title: "Confira a lista completa de estreias de julho nos cinemas",
    date: "24/06/2026 | 20:05",
    author: "Igor Petri",
    category: "Estreias",
    image: ["#7c3aed", "#0f172a"],
    imageUrl: tmdb("uPuVEyoGrtoU9O2sLDhwtKPR78Z", "w780"),
  },
];

